Added imports to __init__.py.
Previously, we were not importing envs and agents inside the root
__init__.py, so this would happen:

    >>> import gym_hanabi
    >>> gym_hanabi.envs
    AttributeError: module 'gym_hanabi' has no attribute 'env'

Now that we import them, this happens:

    >>> import gym_hanabi
    >>> gym_hanabi.envs
    <module 'gym_hanabi.envs' from ...